# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: host-deployment
# spec:
#   replicas: 1              # two Pods total
#   selector:
#     matchLabels:
#       app: worker
#   template:
#     metadata:
#       labels:
#         app: worker
#     spec:
#       containers:
#         - name: host
#           image: maxrerisi/k3s-quick-app:latest
#           ports:
#           - containerPort: 1234
#           # imagePullPolicy: IfNotPresent # DONT USE THIS
#           # (optional) env:
#           # - name: APP_URL
#           #   value: "http://flask-service:1234/data"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask
        image: maxrerisi/k3s-quick-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
  externalIPs:
  - 192.168.64.8